name: Build Qix

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Qix-Linux-x86_64

          - os: windows-latest
            artifact_name: Qix-Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer PyInstaller
        run: python -m pip install pyinstaller

      - name: Construire Qix
        run: pyinstaller --onefile --windowed --clean --name Qix game.py

      # -------------------------
      # Linux
      # -------------------------

      - name: Préparer la version Linux
        if: runner.os == 'Linux'
        run: |
          mkdir -p release
          chmod +x dist/Qix
          tar -czf release/Qix-Linux-x86_64.tar.gz -C dist Qix

      # -------------------------
      # Windows
      # -------------------------

      - name: Préparer la version Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release
          Copy-Item dist/Qix.exe release/Qix-Windows.exe

      # -------------------------
      # Artifacts
      # -------------------------

      - name: Sauvegarder le build Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: Qix-Linux-x86_64
          path: release/Qix-Linux-x86_64.tar.gz

      - name: Sauvegarder le build Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: Qix-Windows
          path: release/Qix-Windows.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger les exécutables
        uses: actions/download-artifact@v4
        with:
          pattern: Qix-*
          path: release
          merge-multiple: true

      - name: Créer la release GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            release/Qix-Linux-x86_64.tar.gz
            release/Qix-Windows.exe